### ISSUE TITLE
Compare Repositories

### ISSUE THREAD

**Issue by phiwut** [SevenOutman/Hubble#3]
Would be cool if you could compare to repositories and look how they race each other

**Comment by SevenOutman** [comment]
@phiwut Nice idea, and it's actually already on the list. PRs are also welcome.

**Comment by SevenOutman** [comment]
@phiwut It's done in 969c9c51d5d26844cdf76bc62f84be0c88118ea5. Here's a demo - [React vs Vue](https://hubble.js.org/repo-race?v=facebook%2Freact&s=vuejs%2Fvue).
